# Generated by Django 4.2.6 on 2023-11-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("password", "0002_password_delete_passwords"),
    ]

    operations = [
        migrations.RenameField(
            model_name="password",
            old_name="hash",
            new_name="ciphertext",
        ),
        migrations.AddField(
            model_name="password",
            name="comment",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
