# Generated by Django 4.2.6 on 2023-11-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("password", "0003_rename_hash_password_ciphertext_password_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="password",
            name="tags",
            field=models.CharField(
                blank=True,
                choices=[
                    ("blue", "blue"),
                    ("red", "red"),
                    ("green", "green"),
                    ("yellow", "yellow"),
                    ("purple", "purple"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
