# Generated by Django 4.2.6 on 2023-11-20 21:09

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):
    dependencies = [
        ("password", "0005_alter_password_ciphertext"),
    ]

    operations = [
        migrations.AddField(
            model_name="password",
            name="username",
            field=django_cryptography.fields.encrypt(
                models.CharField(blank=True, max_length=1000, null=True)
            ),
        ),
        migrations.AlterField(
            model_name="password",
            name="comment",
            field=django_cryptography.fields.encrypt(
                models.CharField(blank=True, max_length=1000, null=True)
            ),
        ),
    ]
